language: android
sudo: false
jdk: oraclejdk8
android:
    components:
        - tools
        - platform-tools
        - build-tools-25.0.0
        - android-25
        - extra-android-m2repository
env:
    - TERM=dumb
script:
    - cd CongressRoutePlanner
    - ./gradlew check lint
cache:
    directories:
        - $HOME/.gradle
