language: android
sudo: false
android:
    components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-23
        - extra-android-m2repository
env:
    - TERM=dumb
script:
    - cd CongressRoutePlanner
    - ./gradlew check lint
    - cat app/build/outputs/lint-results.xml
cache:
    directories:
        - $HOME/.gradle
